//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calculadoraWebService.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        calculadoraWebService.ServiceReference2.HelloWorldResponse HelloWorld(calculadoraWebService.ServiceReference2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<calculadoraWebService.ServiceReference2.HelloWorldResponse> HelloWorldAsync(calculadoraWebService.ServiceReference2.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento prefix del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularExpresionPrefija", ReplyAction="*")]
        calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaResponse CalcularExpresionPrefija(calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularExpresionPrefija", ReplyAction="*")]
        System.Threading.Tasks.Task<calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaResponse> CalcularExpresionPrefijaAsync(calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento expression del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calcular", ReplyAction="*")]
        calculadoraWebService.ServiceReference2.CalcularResponse Calcular(calculadoraWebService.ServiceReference2.CalcularRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calcular", ReplyAction="*")]
        System.Threading.Tasks.Task<calculadoraWebService.ServiceReference2.CalcularResponse> CalcularAsync(calculadoraWebService.ServiceReference2.CalcularRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public calculadoraWebService.ServiceReference2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(calculadoraWebService.ServiceReference2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public calculadoraWebService.ServiceReference2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(calculadoraWebService.ServiceReference2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularExpresionPrefijaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularExpresionPrefija", Namespace="http://tempuri.org/", Order=0)]
        public calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaRequestBody Body;
        
        public CalcularExpresionPrefijaRequest() {
        }
        
        public CalcularExpresionPrefijaRequest(calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularExpresionPrefijaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prefix;
        
        public CalcularExpresionPrefijaRequestBody() {
        }
        
        public CalcularExpresionPrefijaRequestBody(string prefix) {
            this.prefix = prefix;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularExpresionPrefijaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularExpresionPrefijaResponse", Namespace="http://tempuri.org/", Order=0)]
        public calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaResponseBody Body;
        
        public CalcularExpresionPrefijaResponse() {
        }
        
        public CalcularExpresionPrefijaResponse(calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularExpresionPrefijaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalcularExpresionPrefijaResult;
        
        public CalcularExpresionPrefijaResponseBody() {
        }
        
        public CalcularExpresionPrefijaResponseBody(string CalcularExpresionPrefijaResult) {
            this.CalcularExpresionPrefijaResult = CalcularExpresionPrefijaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Calcular", Namespace="http://tempuri.org/", Order=0)]
        public calculadoraWebService.ServiceReference2.CalcularRequestBody Body;
        
        public CalcularRequest() {
        }
        
        public CalcularRequest(calculadoraWebService.ServiceReference2.CalcularRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string expression;
        
        public CalcularRequestBody() {
        }
        
        public CalcularRequestBody(string expression) {
            this.expression = expression;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularResponse", Namespace="http://tempuri.org/", Order=0)]
        public calculadoraWebService.ServiceReference2.CalcularResponseBody Body;
        
        public CalcularResponse() {
        }
        
        public CalcularResponse(calculadoraWebService.ServiceReference2.CalcularResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalcularResult;
        
        public CalcularResponseBody() {
        }
        
        public CalcularResponseBody(string CalcularResult) {
            this.CalcularResult = CalcularResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : calculadoraWebService.ServiceReference2.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<calculadoraWebService.ServiceReference2.WebService1Soap>, calculadoraWebService.ServiceReference2.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        calculadoraWebService.ServiceReference2.HelloWorldResponse calculadoraWebService.ServiceReference2.WebService1Soap.HelloWorld(calculadoraWebService.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            calculadoraWebService.ServiceReference2.HelloWorldRequest inValue = new calculadoraWebService.ServiceReference2.HelloWorldRequest();
            inValue.Body = new calculadoraWebService.ServiceReference2.HelloWorldRequestBody();
            calculadoraWebService.ServiceReference2.HelloWorldResponse retVal = ((calculadoraWebService.ServiceReference2.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<calculadoraWebService.ServiceReference2.HelloWorldResponse> calculadoraWebService.ServiceReference2.WebService1Soap.HelloWorldAsync(calculadoraWebService.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<calculadoraWebService.ServiceReference2.HelloWorldResponse> HelloWorldAsync() {
            calculadoraWebService.ServiceReference2.HelloWorldRequest inValue = new calculadoraWebService.ServiceReference2.HelloWorldRequest();
            inValue.Body = new calculadoraWebService.ServiceReference2.HelloWorldRequestBody();
            return ((calculadoraWebService.ServiceReference2.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaResponse calculadoraWebService.ServiceReference2.WebService1Soap.CalcularExpresionPrefija(calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaRequest request) {
            return base.Channel.CalcularExpresionPrefija(request);
        }
        
        public string CalcularExpresionPrefija(string prefix) {
            calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaRequest inValue = new calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaRequest();
            inValue.Body = new calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaRequestBody();
            inValue.Body.prefix = prefix;
            calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaResponse retVal = ((calculadoraWebService.ServiceReference2.WebService1Soap)(this)).CalcularExpresionPrefija(inValue);
            return retVal.Body.CalcularExpresionPrefijaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaResponse> calculadoraWebService.ServiceReference2.WebService1Soap.CalcularExpresionPrefijaAsync(calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaRequest request) {
            return base.Channel.CalcularExpresionPrefijaAsync(request);
        }
        
        public System.Threading.Tasks.Task<calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaResponse> CalcularExpresionPrefijaAsync(string prefix) {
            calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaRequest inValue = new calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaRequest();
            inValue.Body = new calculadoraWebService.ServiceReference2.CalcularExpresionPrefijaRequestBody();
            inValue.Body.prefix = prefix;
            return ((calculadoraWebService.ServiceReference2.WebService1Soap)(this)).CalcularExpresionPrefijaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        calculadoraWebService.ServiceReference2.CalcularResponse calculadoraWebService.ServiceReference2.WebService1Soap.Calcular(calculadoraWebService.ServiceReference2.CalcularRequest request) {
            return base.Channel.Calcular(request);
        }
        
        public string Calcular(string expression) {
            calculadoraWebService.ServiceReference2.CalcularRequest inValue = new calculadoraWebService.ServiceReference2.CalcularRequest();
            inValue.Body = new calculadoraWebService.ServiceReference2.CalcularRequestBody();
            inValue.Body.expression = expression;
            calculadoraWebService.ServiceReference2.CalcularResponse retVal = ((calculadoraWebService.ServiceReference2.WebService1Soap)(this)).Calcular(inValue);
            return retVal.Body.CalcularResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<calculadoraWebService.ServiceReference2.CalcularResponse> calculadoraWebService.ServiceReference2.WebService1Soap.CalcularAsync(calculadoraWebService.ServiceReference2.CalcularRequest request) {
            return base.Channel.CalcularAsync(request);
        }
        
        public System.Threading.Tasks.Task<calculadoraWebService.ServiceReference2.CalcularResponse> CalcularAsync(string expression) {
            calculadoraWebService.ServiceReference2.CalcularRequest inValue = new calculadoraWebService.ServiceReference2.CalcularRequest();
            inValue.Body = new calculadoraWebService.ServiceReference2.CalcularRequestBody();
            inValue.Body.expression = expression;
            return ((calculadoraWebService.ServiceReference2.WebService1Soap)(this)).CalcularAsync(inValue);
        }
    }
}
