//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calculadoraWebService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        calculadoraWebService.ServiceReference1.HelloWorldResponse HelloWorld(calculadoraWebService.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<calculadoraWebService.ServiceReference1.HelloWorldResponse> HelloWorldAsync(calculadoraWebService.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento prefix del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularExpresionPrefija", ReplyAction="*")]
        calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaResponse CalcularExpresionPrefija(calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularExpresionPrefija", ReplyAction="*")]
        System.Threading.Tasks.Task<calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaResponse> CalcularExpresionPrefijaAsync(calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public calculadoraWebService.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(calculadoraWebService.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public calculadoraWebService.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(calculadoraWebService.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularExpresionPrefijaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularExpresionPrefija", Namespace="http://tempuri.org/", Order=0)]
        public calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaRequestBody Body;
        
        public CalcularExpresionPrefijaRequest() {
        }
        
        public CalcularExpresionPrefijaRequest(calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularExpresionPrefijaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prefix;
        
        public CalcularExpresionPrefijaRequestBody() {
        }
        
        public CalcularExpresionPrefijaRequestBody(string prefix) {
            this.prefix = prefix;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularExpresionPrefijaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularExpresionPrefijaResponse", Namespace="http://tempuri.org/", Order=0)]
        public calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaResponseBody Body;
        
        public CalcularExpresionPrefijaResponse() {
        }
        
        public CalcularExpresionPrefijaResponse(calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularExpresionPrefijaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalcularExpresionPrefijaResult;
        
        public CalcularExpresionPrefijaResponseBody() {
        }
        
        public CalcularExpresionPrefijaResponseBody(string CalcularExpresionPrefijaResult) {
            this.CalcularExpresionPrefijaResult = CalcularExpresionPrefijaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : calculadoraWebService.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<calculadoraWebService.ServiceReference1.WebService1Soap>, calculadoraWebService.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        calculadoraWebService.ServiceReference1.HelloWorldResponse calculadoraWebService.ServiceReference1.WebService1Soap.HelloWorld(calculadoraWebService.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            calculadoraWebService.ServiceReference1.HelloWorldRequest inValue = new calculadoraWebService.ServiceReference1.HelloWorldRequest();
            inValue.Body = new calculadoraWebService.ServiceReference1.HelloWorldRequestBody();
            calculadoraWebService.ServiceReference1.HelloWorldResponse retVal = ((calculadoraWebService.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<calculadoraWebService.ServiceReference1.HelloWorldResponse> calculadoraWebService.ServiceReference1.WebService1Soap.HelloWorldAsync(calculadoraWebService.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<calculadoraWebService.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            calculadoraWebService.ServiceReference1.HelloWorldRequest inValue = new calculadoraWebService.ServiceReference1.HelloWorldRequest();
            inValue.Body = new calculadoraWebService.ServiceReference1.HelloWorldRequestBody();
            return ((calculadoraWebService.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaResponse calculadoraWebService.ServiceReference1.WebService1Soap.CalcularExpresionPrefija(calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaRequest request) {
            return base.Channel.CalcularExpresionPrefija(request);
        }
        
        public string CalcularExpresionPrefija(string prefix) {
            calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaRequest inValue = new calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaRequest();
            inValue.Body = new calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaRequestBody();
            inValue.Body.prefix = prefix;
            calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaResponse retVal = ((calculadoraWebService.ServiceReference1.WebService1Soap)(this)).CalcularExpresionPrefija(inValue);
            return retVal.Body.CalcularExpresionPrefijaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaResponse> calculadoraWebService.ServiceReference1.WebService1Soap.CalcularExpresionPrefijaAsync(calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaRequest request) {
            return base.Channel.CalcularExpresionPrefijaAsync(request);
        }
        
        public System.Threading.Tasks.Task<calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaResponse> CalcularExpresionPrefijaAsync(string prefix) {
            calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaRequest inValue = new calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaRequest();
            inValue.Body = new calculadoraWebService.ServiceReference1.CalcularExpresionPrefijaRequestBody();
            inValue.Body.prefix = prefix;
            return ((calculadoraWebService.ServiceReference1.WebService1Soap)(this)).CalcularExpresionPrefijaAsync(inValue);
        }
    }
}
